FROM debian:bullseye-slim AS prepare

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    nasm yasm \
    pkg-config \
    autoconf automake libtool \
    cmake meson ninja-build \
    python3 python3-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libtheora-dev \
    libsndfile1-dev \
    libfribidi-dev \
    libharfbuzz-dev \
    libatomic1 \
    libturbojpeg0-dev \
    libjpeg62-turbo-dev \
    gperf \
    x265 \
    libx265-dev \
    ca-certificates \
    wget \
    tar

WORKDIR /work

COPY prepare-gcc-15-minimal.sh /work/prepare-gcc-15-minimal.sh
RUN chmod +x /work/prepare-gcc-15-minimal.sh
RUN /work/prepare-gcc-15-minimal.sh

FROM prepare AS static-libs

COPY prepare-static-libs.sh /work/prepare-static-libs-debian.sh
RUN chmod +x /work/prepare-static-libs-debian.sh
RUN /work/prepare-static-libs-debian.sh

COPY build-handbrake-alpaquita.sha /work/build-handbrake-debian.sha
RUN chmod +x /work/build-handbrake-debian.sha
RUN /work/build-handbrake-debian.sha
